server:
  max_cache_bytes: 2048
  base_path: "/_gocache/"
  replicas: 50
  default_group: "default"
  ##注册中心地址
  register_center: "http://localhost:8000/register"
preTask:
  data_type: "json"
  file_path: "./data.json"
  dsn: ""
